const { runMain } = require("module");

module.exports = {
  admins: ["614063626239606805", "850409862792871966"],
  invitelink:
    "https://discord.com/oauth2/authorize?client_id=888249861605048350&permissions=2147806288&&scope=bot%20applications.commands&redirect_url=riftyporo.vercel.app",
  latestfeed: "[Buy me a coffee](https://www.buymeacoffee.com/hansdev)",
  token: process.env.token,
  prefix: "r!",
  debug: true,
  gameMode: {
    ranked: 110001,
    rank: 110001,
    duo: 120001,
    rankedduo: 120001,
    rankduo: 120001,
    pvp: 100302,
    aram: 100202,
  },
  region: {
    euw: "eu",
    europe: "eu",
    eu: "eu",
    eune: "eu",
    lan: "na",
    las: "na",
    northamerica: "na",
    na: "na",
    asia: "sea",
    sea: "sea",
  },
  tier: {
    all_tiers: "allTiers",
    iron: 1,
    bronze: 5,
    silver: 9,
    gold: 13,
    platinum: 17,
    emerald: 21,
    diamond: 25,
    master: 29,
    grandmaster: 29,
    challenger: 29,
  },
  wildriftfire: {
    nunu: "nunu-amp-willump",
    nunuandwillump: "nunu-amp-willump",
    willump: "nunu-amp-willump",
    leesin: "lee-sin",
    drmundo: "dr-mundo",
    jarvan: "jarvan-iv",
    jarvaniv: "jarvan-iv",
    jarvan4: "jarvan-iv",
    xinzhao: "xin-zhao",
    twistedfate: "twisted-fate",
    aurelionsol: "aurelion-sol",
    asol: "aurelion-sol",
    masteryi: "master-yi",
    missfortune: "miss-fortune",
    khazix: "khazix",
    kaisa: "kaisa",
  },
  wildriftguides: {
    nunu: "nunu-willump",
    nunuandwillump: "nunu-willump",
    willump: "nunu-willump",
    leesin: "lee-sin",
    drmundo: "dr-mundo",
    jarvan: "jarvan-iv",
    jarvaniv: "jarvan-iv",
    jarvan4: "jarvan-iv",
    xinzhao: "xin-zhao",
    twistedfate: "twisted-fate",
    aurelionsol: "aurelion-sol",
    asol: "aurelion-sol",
    masteryi: "master-yi",
    missfortune: "miss-fortune",
    khazix: "kha-zix",
    kaisa: "kaisa",
  },
  rankedboost: {
    nunu: "nunu",
    nunuandwillump: "nunu",
    willump: "nunu",
    leesin: "lee-sin",
    drmundo: "dr-mundo",
    jarvan: "jarvan-iv",
    jarvaniv: "jarvan-iv",
    jarvan4: "jarvan-iv",
    xinzhao: "xin-zhao",
    twistedfate: "twisted-fate",
    aurelionsol: "aurelion-sol",
    asol: "aurelion-sol",
    masteryi: "master-yi",
    missfortune: "miss-fortune",
    khazix: "kha-zix",
    kaisa: "kaisa",
  },
  mobafire: {
    nunu: "nunu-amp-willump",
    nunuandwillump: "nunu-amp-willump",
    willump: "nunu-amp-willump",
    leesin: "lee-sin",
    drmundo: "dr-mundo",
    jarvan: "jarvan-iv",
    jarvaniv: "jarvan-iv",
    jarvan4: "jarvan-iv",
    xinzhao: "xin-zhao",
    twistedfate: "twisted-fate",
    aurelionsol: "aurelion-sol",
    asol: "aurelion-sol",
    masteryi: "master-yi",
    missfortune: "miss-fortune",
    khazix: "khazix",
    kaisa: "kaisa",
  },
};
